### ISSUE TITLE
pypi package?

### ISSUE THREAD

**Issue by dvolgyes** [diregoblin/poisson_disc_sampling#2]
Hi,

Don't get me wrong, it is already awesome that you followed up and published a working code.
But it could be even better if you could make pypi package from it. :)

**Comment by diregoblin** [comment]
Thanks for the interest! I'll look into making a package from this, the PyPI tutorial seems pretty straightforward

**Comment by dvolgyes** [comment]
Pypi: it is, and I am very happy with `twine`, but `poetry` is also quite straightforward. 
My only recommendation is: play with the test server first. But when 
`pip install .` works, then you are basically done, the server part is not a big deal. :) 

If you get lost, take a look at the Makefile here:
https://github.com/dvolgyes/flake8_tensors
I use it for deploying mine to pypy test server and server.

I had some trouble to find the proper pypirc settings, the code above uses something like this:

```
[distutils]
index-servers=
    pypi
    testpypi

[pypi]
username: __token__
password: pypi-Ag...

[testpypi]
repository = https://test.pypi.org/legacy/
username: __token__
password: pypi-Ag...
```
The password tokens are cut at the ... part, obviously, but the username really is `__token__`.
At the time, this has confused me a bit. 

Anyway, it is not too complicated and probably the documentation got more detailed in the meantime. :) 
Good luck!

**Comment by diregoblin** [comment]
Thanks for the detailed reply! I've published this to PyPI as ``poisson_disc`` (https://pypi.org/project/poisson-disc/). I've checked ``pip`` installation from the remote, it seems to work for me. Would be great if you can check it and confirm if it works for you also.

**Comment by dvolgyes** [comment]
It does work! :)
Well, I plotted the basic sampling, not the hypersphere, but it looked good.
Thanks again!

**Comment by diregoblin** [comment]
Good to hear that!

Also, a word of warning if you want to use this for high-dimensional spaces, e.g. in ML: the costs grow exponentially with the number of dimensions due to the way the neighbour lookup is implemented. It's fine in 2D and 3D, but then it gets costly.

I personally only need the 3D case, so I'm not planning to look into optimizing this anytime soon. An alternative is to place all points in a k-d tree and use that to find the closest point, that would make the lookup cost ``O(log(number_of_samples))``

**Comment by dvolgyes** [comment]
Thanks for the warning. 
Actually, I do would like to use it in ML, but in a different way, 
e.g. sampling geographical regions somewhat uniformly but still randomly. 
And in next epoch it can get a new distribution. 

Probably the only part where speed could matter is around 4-6 dimensions, 
because above that the curse of dimensionality will hit anyway. 

But thanks for the warning, I will keep the cost part in mind. :)
